#!/usr/bin/env python

import vboxn.ui


def main():
    vboxn.ui.main()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nUser ended program.')

